# Generated by Django 3.0.1 on 2019-12-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20191220_1224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Article',
        ),
    ]
